<a href="https://colab.research.google.com/github/Isamaoz/CE888---Data-Science-and-Decision-Making/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**FIRST LABORATORY**
##Isamiri Ortiz Blanco


## Questions to be done during the lab:

1. Create a (4 x 2) integer array and print it's attributes

2. Create an array of dimension (1,10) and sort it in ascending and descending order

3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

4. Stack two arrays of any size horizontally and vertically

5. Create two array of same size and find commom elements

6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

7. Create an array of size 100 and  compute the mean, median, standard deviation. 

8. Normalize a 5x5 random matrix 

9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?



In [0]:
import numpy as np

In [4]:
# 1. 4x2 integer array
a = np.array([[0, 1],
              [2, 3],
              [4, 5],
              [6, 7]])
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [5]:
print(a.shape)

(4, 2)


In [6]:
# 2. array of dimension (1,10) 
b = np.array([5,6,2,7,12,56,3,1,9,8])
print("Sorting in ascending order:")
print(np.sort(b))
print("Sorting in descending order:")
print(-np.sort(-b))


Sorting in ascending order:
[ 1  2  3  5  6  7  8  9 12 56]
Sorting in descending order:
[56 12  9  8  7  6  5  3  2  1]


In [7]:
# 3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(c)
c = np.array([c[0:3],
              c[3:6],
              c[6:9]])
print(c)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# 4. Stack two arrays of any size horizontally and vertically
d = np.array([1,2,3,4])
e = np.array([5,6,7,8])

# Stack horizontally
print(np.stack((d,e)))

# Stack vertically
print(np.stack((d,e), axis=-1))

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [9]:
# 5. Create two array of same size and find commom elements
f = [1,2,3,9,5]
g = [5,7,2,9,10]
np.intersect1d(f,g)

array([2, 5, 9])

In [10]:
# 6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column
x = np.array([[1,2,3,4,5],
              [61,87,8,92,10],
              [111,2,138,14,15],
              [116,57,18,109,20],
              [31,2,45,6,0]])
#Minimum in rows
print("Minimum values in rows:")
for y in range(5):
  print(np.min(x[y]))
print("Maximum values in rows:")  
for y in range(5):
  print(np.max(x[y]))
print("Minimum values in columns:")
for y in range(5):
  print(np.min(x[:,y]))
print("Maximum values in columns:")
for y in range(5):
  print(np.max(x[:,y]))

Minimum values in rows:
1
8
2
18
0
Maximum values in rows:
5
92
138
116
45
Minimum values in columns:
1
2
3
4
0
Maximum values in columns:
116
87
138
109
20


In [11]:
# 7. Create an array of size 100 and compute the mean, median, standard deviation.
h=np.random.rand(1,100)
print(h)
print("Mean of the array:")
print(np.mean(h))
print("Median of the array:")
print(np.median(h))
print("Standard deviation of the array:")
print(np.std(h))

[[0.53322616 0.35372714 0.04070182 0.48434489 0.22422196 0.99878889
  0.9691788  0.94232115 0.91496752 0.59606116 0.48823341 0.44293172
  0.89221934 0.57246933 0.16611995 0.23942561 0.77644532 0.14747025
  0.81091819 0.75370095 0.66342287 0.01342854 0.73843236 0.3451445
  0.00190823 0.31672851 0.76632006 0.58979726 0.55664935 0.48895936
  0.07345821 0.5244453  0.20978206 0.5124464  0.87184458 0.6881649
  0.41841818 0.6077956  0.31341362 0.90466153 0.80647701 0.87784404
  0.92491737 0.99423697 0.46603409 0.85856903 0.30396732 0.78055538
  0.50583467 0.25501972 0.29326018 0.82215226 0.13546003 0.85973686
  0.05477359 0.9720545  0.1989425  0.2984104  0.97598303 0.85134254
  0.17920558 0.35971433 0.64201623 0.56474165 0.84578433 0.21039374
  0.73997176 0.79014589 0.38545522 0.2105519  0.77175305 0.01529085
  0.23514162 0.56049111 0.0141339  0.22601303 0.72852192 0.3659927
  0.02555374 0.85514215 0.91723439 0.85851107 0.62727743 0.02168459
  0.62857012 0.57005913 0.06095142 0.42881226 0.226

In [12]:
# 8. Normalize a 5x5 random matrix
i = np.random.rand(5,5)
print(i)
i_max, i_min = i.max(), i.min()
i = (i - i_min)/(i_max - i_min)
print(i)
#Use sckit learn to make it easier

[[0.74590269 0.42141289 0.10137174 0.61371558 0.12876335]
 [0.53779056 0.54640111 0.56064198 0.56481756 0.39139648]
 [0.94457713 0.44281357 0.58828032 0.75489272 0.73657079]
 [0.28776436 0.62203449 0.41901809 0.61151165 0.32068251]
 [0.20866124 0.71575559 0.75260791 0.68629031 0.53146364]]
[[0.76438192 0.37955301 0.         0.60761452 0.0324851 ]
 [0.5175712  0.52778288 0.54467185 0.54962388 0.34395504]
 [1.         0.40493317 0.57744956 0.77504364 0.75331474]
 [0.22105245 0.61748034 0.3767129  0.60500076 0.26009176]
 [0.12724006 0.72862894 0.77233397 0.69368457 0.51006778]]


In [13]:
# 9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?
# Getting the transponse of the multidimensional array, so that each row multiplies a column 
j = np.random.rand(4,4,3)
k = np.random.rand(4,4)
# print(j)
# print(k)
# res = j * np.transpose(np.array([k,]*3))
# print(res)

j * k[:,:,None]

array([[[0.22844526, 0.59777524, 0.21466445],
        [0.15074315, 0.4564341 , 0.09490294],
        [0.19355769, 0.03816401, 0.12146041],
        [0.1297865 , 0.315621  , 0.17219077]],

       [[0.3254464 , 0.60134151, 0.60100924],
        [0.00798972, 0.09560647, 0.28388254],
        [0.41631185, 0.096536  , 0.54284698],
        [0.021195  , 0.04878682, 0.01063763]],

       [[0.28555149, 0.67837052, 0.83018336],
        [0.38645409, 0.3940568 , 0.29162075],
        [0.13363275, 0.27897613, 0.35621158],
        [0.16799648, 0.17355133, 0.12481229]],

       [[0.1492741 , 0.33248831, 0.01081682],
        [0.32245226, 0.06522247, 0.47151405],
        [0.23131131, 0.01980643, 0.32098351],
        [0.29096256, 0.07972388, 0.05661389]]])